# Generated by Django 3.2.16 on 2023-07-12 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hometaskresult',
            old_name='home_task',
            new_name='home_tasks',
        ),
        migrations.RenameField(
            model_name='hometaskresult',
            old_name='student',
            new_name='students',
        ),
    ]
