# Generated by Django 3.2.16 on 2023-07-18 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hometaskresult',
            old_name='home_task',
            new_name='home_tasks',
        ),
        migrations.RenameField(
            model_name='hometaskresult',
            old_name='student',
            new_name='students',
        ),
        migrations.AlterField(
            model_name='lecture',
            name='presentation',
            field=models.FileField(upload_to='media'),
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('rating', models.CharField(choices=[('done', 'Done'), ('not done', 'Not done'), ('not provided', 'Not provided'), ('overdue', 'Overdue')], max_length=12)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.teacher')),
                ('home_task_result', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='apps.hometaskresult')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('comment', models.CharField(max_length=200, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apps.mark')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
