# Generated by Django 3.2.16 on 2023-07-06 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='name',
        ),
    ]
