# Generated by Django 3.2.16 on 2023-07-12 09:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_auto_20230712_0704'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('rating', models.CharField(choices=[('done', 'Done'), ('not done', 'Not done'), ('not provided', 'Not provided'), ('overdue', 'Overdue')], max_length=12)),
                ('home_task_result', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='apps.hometaskresult')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
