# Generated by Django 3.2.16 on 2023-07-06 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_auto_20230706_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hometask',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='hometask',
            name='name',
        ),
    ]
