# Generated by Django 3.2.16 on 2023-08-25 07:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_auto_20230825_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountconfirmation',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 25, 11, 29, 12, 287919, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 25, 11, 29, 12, 238994, tzinfo=utc)),
        ),
    ]
