# Generated by Django 3.2.16 on 2023-07-20 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_mark_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hometaskresult',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.student'),
        ),
    ]
