# Generated by Django 3.2.16 on 2023-07-06 11:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_auto_20230706_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home_task',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('description', models.TextField(max_length=1000)),
                ('lectures', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='apps.lecture')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IntermediateCompletedHome_taskStudent',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('home_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.home_task')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='HomeTask',
        ),
        migrations.AddField(
            model_name='home_task',
            name='students',
            field=models.ManyToManyField(through='apps.IntermediateCompletedHome_taskStudent', to='apps.Student'),
        ),
    ]
