# Generated by Django 3.2.16 on 2023-07-12 12:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_mark'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('comment', models.CharField(max_length=200, null=True)),
                ('created_by', models.CharField(max_length=36)),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apps.mark')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
