# Generated by Django 3.2.16 on 2023-08-28 05:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_auto_20230825_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='participants_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='accountconfirmation',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 28, 9, 5, 42, 108596, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 28, 9, 5, 42, 35287, tzinfo=utc)),
        ),
    ]
