# Generated by Django 3.2.16 on 2023-09-06 12:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_auto_20230828_0505'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='invited_by',
            field=models.CharField(default='', max_length=200, verbose_name='Invited by'),
        ),
        migrations.AlterField(
            model_name='accountconfirmation',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 6, 16, 12, 40, 144840, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 6, 16, 12, 40, 82000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='topic',
            field=models.CharField(max_length=100),
        ),
    ]
