# Generated by Django 3.2.16 on 2023-07-06 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_auto_20230706_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='intermediatecompletedhome_taskstudent',
            name='answer',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
