# Generated by Django 3.2.16 on 2023-07-06 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_intermediatecompletedhome_taskstudent_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='completed_home_task',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='apps.intermediatecompletedhome_taskstudent'),
        ),
    ]
